<?php
if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_color-pack-customization',
		'title' => 'Color Pack Customization',
		'fields' => array (
			array (
				'key' => 'field_585a70cb9752b',
				'label' => 'Text Colour',
				'name' => 'text_colour',
				'type' => 'color_picker',
				'default_value' => '#576366',
			),
			array (
				'key' => 'field_585a73fd23809',
				'label' => 'Heading Colour',
				'name' => 'heading_colour',
				'type' => 'color_picker',
				'required' => 1,
				'default_value' => '#576366',
			),
			array (
				'key' => 'field_585a75ef90d3d',
				'label' => 'Link Colour',
				'name' => 'link_colour',
				'type' => 'color_picker',
				'required' => 1,
				'default_value' => '#5fcf80',
			),
			array (
				'key' => 'field_585a76aa7caa1',
				'label' => 'Link Hover Colour',
				'name' => 'link_hover_colour',
				'type' => 'color_picker',
				'required' => 1,
				'default_value' => '#00ce3d',
			),
			array (
				'key' => 'field_585a78cf0c0a5',
				'label' => 'Background Colour',
				'name' => 'background_colour',
				'type' => 'color_picker',
				'required' => 1,
				'default_value' => '#ffffff',
			),
			array (
				'key' => 'field_585a794ee5aab',
				'label' => 'Primary Button Colour',
				'name' => 'primary_button_colour',
				'type' => 'color_picker',
				'required' => 1,
				'default_value' => '#5fcf80',
			),
			array (
				'key' => 'field_585a79e9078f9',
				'label' => 'Primary Button Hover Colour',
				'name' => 'primary_button_hover_colour',
				'type' => 'color_picker',
				'required' => 1,
				'default_value' => '#00ce3d',
			),
			array (
				'key' => 'field_585a7a73f04e9',
				'label' => 'Primary Button Text Colour',
				'name' => 'primary_button_text_colour',
				'type' => 'color_picker',
				'required' => 1,
				'default_value' => '#ffffff',
			),
			array (
				'key' => 'field_585a7ad1f04ea',
				'label' => 'Primary Button Hover Text Colour',
				'name' => 'primary_button_hover_text_colour',
				'type' => 'color_picker',
				'required' => 1,
				'default_value' => '#ffffff',
			),
			array (
				'key' => 'field_585a7b61f04eb',
				'label' => 'Primary Button Icon Colour',
				'name' => 'primary_button_icon_colour',
				'type' => 'color_picker',
				'required' => 1,
				'default_value' => '#ffffff',
			),
			array (
				'key' => 'field_585a7b9ef04ec',
				'label' => 'Primary Button Hover Icon Colour',
				'name' => 'primary_button_hover_icon_colour',
				'type' => 'color_picker',
				'required' => 1,
				'default_value' => '#ffffff',
			),
			array (
				'key' => 'field_585a7bddf04ed',
				'label' => 'Icon Colour',
				'name' => 'icon_colour',
				'type' => 'color_picker',
				'required' => 1,
				'default_value' => '#5fcf80',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'color_packs',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_post-header',
		'title' => 'Post Header',
		'fields' => array (
			array (
				'key' => 'field_585a806592965',
				'label' => 'Override Color Pack',
				'name' => 'override_colorpack',
				'type' => 'true_false',
				'message' => 'Want to Override Page Header Colorpack?',
				'default_value' => 0,
			),
			array (
				'key' => 'field_585a80b88318d',
				'label' => 'Header Color Pack',
				'name' => 'header_color_pack',
				'type' => 'post_object',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_585a806592965',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'post_type' => array (
					0 => 'color_packs',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_585a8497949b5',
				'label' => 'Transparent Menu',
				'name' => 'transparent_menu',
				'type' => 'true_false',
				'instructions' => 'It will make header menu transparent before its change on scroll.',
				'message' => 'Transparent Header',
				'default_value' => 0,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'post',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_sparta-page-options',
		'title' => 'Sparta Page Options',
		'fields' => array (
			array (
				'key' => 'field_585aa4915587c',
				'label' => 'Page Header',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_585b797f10057',
				'label' => 'Transparent Menu',
				'name' => 'transparent_menu',
				'type' => 'true_false',
				'message' => 'Check this if you want transparent Menu before change',
				'default_value' => 0,
			),
			array (
				'key' => 'field_585ab69774ea9',
				'label' => 'Show Header',
				'name' => 'show_header',
				'type' => 'true_false',
				'message' => 'Do you want page header to be shown?',
				'default_value' => 1,
			),
			array (
				'key' => 'field_585aa37455879',
				'label' => 'Header Text',
				'name' => 'header_text',
				'type' => 'text',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_585ab69774ea9',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_585aa3aa5587a',
				'label' => 'Sub Header Text',
				'name' => 'sub_header_text',
				'type' => 'text',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_585ab69774ea9',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_585aa3d05587b',
				'label' => 'Header Type',
				'name' => 'header_type',
				'type' => 'select',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_585ab69774ea9',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'choices' => array (
					'h1' => 'H1',
					'h2' => 'H2',
					'h3' => 'H3',
					'h4' => 'H4',
					'h5' => 'H5',
					'h6' => 'H6',
				),
				'default_value' => 'h1',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_585aa6d72432a',
				'label' => 'Header Color Pack',
				'name' => 'header_color_pack',
				'type' => 'post_object',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_585ab69774ea9',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'post_type' => array (
					0 => 'color_packs',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_585aa798b72ca',
				'label' => 'Override Header Text Color',
				'name' => 'override_header_color',
				'type' => 'true_false',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_585ab69774ea9',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'message' => 'Check if you want to change color of header to something other then defined in colorpack',
				'default_value' => 0,
			),
			array (
				'key' => 'field_585aa7acb72cb',
				'label' => 'Heading Color',
				'name' => 'heading_color',
				'type' => 'color_picker',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_585ab69774ea9',
							'operator' => '==',
							'value' => '1',
						),
						array (
							'field' => 'field_585aa798b72ca',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '#000',
			),
			array (
				'key' => 'field_585aa96acc3c0',
				'label' => 'Sub Header Type',
				'name' => 'sub_header_type',
				'type' => 'select',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_585ab69774ea9',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'choices' => array (
					'normal' => 'Normal Paragraph',
					'lead' => 'Lead Paragraph',
				),
				'default_value' => 'normal',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_585aaaef7743b',
				'label' => 'Header Text Size',
				'name' => 'header_text_size',
				'type' => 'select',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_585ab69774ea9',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'choices' => array (
					25 => 'Normal',
					36 => 'Big (36px)',
					48 => 'Bigger (48px)',
					60 => 'Super (60px)',
					96 => 'Hyper (96px)',
				),
				'default_value' => 36,
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_585aac0329341',
				'label' => 'Header Font Weight',
				'name' => 'header_font_weight',
				'type' => 'select',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_585ab69774ea9',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'choices' => array (
					400 => 'Regular',
					'bolder' => 'Black',
					700 => 'Bold',
					'lighter' => 'Light',
				),
				'default_value' => 400,
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_585aad2feeae3',
				'label' => 'Header Font Alignment',
				'name' => 'header_font_alignment',
				'type' => 'select',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_585ab69774ea9',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'choices' => array (
					'text-left' => 'Left',
					'text-center' => 'Center',
					'text-right' => 'Right',
					'text-justify' => 'Justify',
				),
				'default_value' => 'text-left',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_585aae25764aa',
				'label' => 'Header Underline',
				'name' => 'header_underline',
				'type' => 'true_false',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_585ab69774ea9',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'message' => 'Check the box if you want line below heading text',
				'default_value' => 0,
			),
			array (
				'key' => 'field_585aaef4e66c9',
				'label' => 'Header Underline Size',
				'name' => 'header_underline_size',
				'type' => 'select',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_585ab69774ea9',
							'operator' => '==',
							'value' => '1',
						),
						array (
							'field' => 'field_585aae25764aa',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'choices' => array (
					'underline-normal' => 'Normal (72px)',
					'underline-small' => 'Small (48px)',
				),
				'default_value' => 'underline-normal',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_585aafbeb954d',
				'label' => 'Fade out when leaving page',
				'name' => 'fade_out_when_leaving_page',
				'type' => 'true_false',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_585ab69774ea9',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'message' => 'Do you want page header to fade out on scroll?',
				'default_value' => 0,
			),
			array (
				'key' => 'field_585ab0412fd4b',
				'label' => 'Extra Classes',
				'name' => 'extra_classes',
				'type' => 'text',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_585ab69774ea9',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => 'Space Separated',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_585ab0ce4e754',
				'label' => 'Margin Top',
				'name' => 'margin_top',
				'type' => 'select',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_585ab69774ea9',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'choices' => array (
					0 => 'None',
					24 => 'Short (24px)',
					48 => 'Medium (48px)',
					72 => 'Normal (72px)',
					92 => 'Tall (92px)',
				),
				'default_value' => 24,
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_585ab1264e755',
				'label' => 'Margin Bottom',
				'name' => 'margin_bottom',
				'type' => 'select',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_585ab69774ea9',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'choices' => array (
					0 => 'None',
					24 => 'Short (24px)',
					48 => 'Medium (48px)',
					72 => 'Normal (72px)',
					92 => 'Tall (92px)',
				),
				'default_value' => 24,
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_585ab1d26ceaa',
				'label' => 'Header Overlay Color',
				'name' => 'overlay_color',
				'type' => 'color_picker',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_585ab69774ea9',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
			),
			array (
				'key' => 'field_585ab33af8ad1',
				'label' => 'Overlay Grid',
				'name' => 'overlay_grid',
				'type' => 'select',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_585ab69774ea9',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'choices' => array (
					0 => 0,
					10 => 10,
					20 => 20,
					30 => 30,
					40 => 40,
					50 => 50,
					60 => 60,
					70 => 70,
					80 => 80,
					90 => 90,
					100 => 100,
				),
				'default_value' => 0,
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_585ab423993ef',
				'label' => 'Background Image',
				'name' => 'background_image',
				'type' => 'image',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_585ab69774ea9',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'save_format' => 'url',
				'preview_size' => 'medium',
				'library' => 'all',
			),
			array (
				'key' => 'field_585ab4a6f95ee',
				'label' => 'Background Image Size',
				'name' => 'background_image_size',
				'type' => 'select',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_585ab69774ea9',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'choices' => array (
					'100%' => 'Full Width',
					'auto' => 'Actual Size',
				),
				'default_value' => 'auto',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_585ab539eb03f',
				'label' => 'Background Image Repeat',
				'name' => 'background_image_repeat',
				'type' => 'select',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_585ab69774ea9',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'choices' => array (
					'no-repeat' => 'No Repeat',
					'repeat-x' => 'Repeat Horizontally',
					'repeat-y' => 'Repeat Vertically',
					'repeat' => 'Repeat Horizontally & Vertically',
				),
				'default_value' => 'no-repeat',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_585ab5af7170b',
				'label' => 'Background Image Vertical Position',
				'name' => 'background_image_vertical_position',
				'type' => 'number',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_585ab69774ea9',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => 0,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '-100',
				'max' => 100,
				'step' => 1,
			),
			array (
				'key' => 'field_585ab63977831',
				'label' => 'Background Image Attachment',
				'name' => 'background_image_attachment',
				'type' => 'select',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_585ab69774ea9',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'choices' => array (
					'scroll' => 'Scroll',
					'fixed' => 'Fixed',
				),
				'default_value' => 'scroll',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_585b770adc983',
				'label' => 'Layout',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_585b7720dc984',
				'label' => 'Page Layout',
				'name' => 'page_layout',
				'type' => 'select',
				'choices' => array (
					'Right Sidebar' => 'Right Sidebar',
					'Left Sidebar' => 'Left Sidebar',
					'No Sidebar' => 'No Sidebar',
					'No Sidebar Narrow' => 'No Sidebar Narrow',
					'No Sidebar Wide' => 'No Sidebar Wide',
				),
				'default_value' => 'Right Sidebar',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_585b78a10aec9',
				'label' => 'Sidebar',
				'name' => 'sidebar',
				'type' => 'sidebar_selector',
				'required' => 1,
				'allow_null' => 0,
				'default_value' => '',
			),
			array (
				'key' => 'field_585f63899a411',
				'label' => 'Content Margin',
				'name' => 'content_margin',
				'type' => 'true_false',
				'message' => 'Check This if you want some margin on top & bottom of page content.',
				'default_value' => 0,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'page',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}